apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: django-test-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: django-test-app
spec:
  source:
    git:
      url: https://github.com/trevorputbrese/tap-django-test
      ref:
        branch: main
